/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario_grafico_videos_20;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author C.andres
 */
public class Formulario_1 extends javax.swing.JFrame {

    /**
     * Creates new form Formulario_1
     */
    public Formulario_1() {
        initComponents();
        //CODIGO PARA UBICAR FORMULARIO AL CENTRO DE LA PANTALLA
        this.setLocationRelativeTo(null);
        //CODIGO PARA AJUSTAR IMAGEN AL LABEL SELECCIONADO POR DEFECTO
        this.rbmasculino.setSelected(true);
        
     /*   ImageIcon fondo =new ImageIcon("src/newpackage\\paisaje.png");
        Icon icono = new ImageIcon(fondo.getImage().getScaledInstance(lblfondo.getWidth(), lblfondo.getHeight(), Image.SCALE_DEFAULT));
      lblfondo.setIcon(icono);
      this.repaint();*/
      //MOSTRAR EL BUTTON
      //MOSTRAR EL RADIO BUTTON MASCULINO SELECCIONADO POR DEFECTO
      this.rbmasculino.setSelected(true);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtapp = new javax.swing.JTextField();
        txtapm = new javax.swing.JTextField();
        txtnom1 = new javax.swing.JTextField();
        txtnom2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        rbmasculino = new javax.swing.JRadioButton();
        rbfemenino = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        chksoltero = new javax.swing.JCheckBox();
        chkcasado = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbbdia = new javax.swing.JComboBox<>();
        cbbmes = new javax.swing.JComboBox<>();
        cbbanio = new javax.swing.JComboBox<>();
        btnprocesar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DATOS DEL FORMULARIO");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FORMULARIO DE DATOS INFORMATIVOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Generales"));
        jPanel1.setOpaque(false);

        jLabel2.setText("Apellido paterno:");

        jLabel3.setText("Apellido materno:");

        jLabel4.setText("Primer nombre:");

        jLabel5.setText("Segundo nombre:");

        txtapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtappActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnom2, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtnom1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                .addComponent(txtapm))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35)
                        .addComponent(txtapp)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtapp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtapm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtnom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(txtnom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 63, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Genero"));
        jPanel2.setOpaque(false);

        buttonGroup1.add(rbmasculino);
        rbmasculino.setText("Masculino");
        rbmasculino.setOpaque(false);
        rbmasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmasculinoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbfemenino);
        rbfemenino.setText("Femenino");
        rbfemenino.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(rbmasculino)
                .addGap(48, 48, 48)
                .addComponent(rbfemenino)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbfemenino)
                    .addComponent(rbmasculino))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 236, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado Civil"));
        jPanel3.setOpaque(false);

        chksoltero.setText("Soltero(a)");
        chksoltero.setOpaque(false);

        chkcasado.setText("Casado(a)");
        chkcasado.setOpaque(false);
        chkcasado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkcasadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chksoltero)
                    .addComponent(chkcasado))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chksoltero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkcasado)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 172, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de Nacimiento"));
        jPanel4.setOpaque(false);

        jLabel6.setText("Dia");

        jLabel7.setText("Mes");

        jLabel8.setText("Año");

        cbbdia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbbdia.setOpaque(false);

        cbbmes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        cbbmes.setOpaque(false);

        cbbanio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", " " }));
        cbbanio.setOpaque(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(47, 47, 47)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(52, 52, 52))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbbdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbbmes, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbbanio, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 63, 255, -1));

        btnprocesar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/acp.png"))); // NOI18N
        btnprocesar.setText("Procesar");
        btnprocesar.setOpaque(false);
        btnprocesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprocesarActionPerformed(evt);
            }
        });
        getContentPane().add(btnprocesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        btnlimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/canc.png"))); // NOI18N
        btnlimpiar.setText("Limpiar");
        btnlimpiar.setOpaque(false);
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/next.png"))); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.setOpaque(false);
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 311, -1, -1));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/paisaje.png"))); // NOI18N
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtappActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtappActionPerformed

    private void rbmasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbmasculinoActionPerformed

    private void chkcasadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkcasadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkcasadoActionPerformed

    private void btnprocesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprocesarActionPerformed
       
        String nombre1, nombre2, apellidop,apellidom;
        nombre1 = txtnom1.getText();
        nombre2 = txtnom2.getText();
        apellidop = txtapp.getText();
         apellidom = txtapm.getText();
         
         //CODIGO PARA DATOS GENERALES
         if(txtnom1.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Ingrese su primer nombre");
             return;  // para que no avance al siguiente formulario
         }
          if(txtapp.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Ingrese su primer apellido");
             return;  // para que no avance al siguiente formulario
         }
           if(txtapm.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Ingrese su segundo apellido");
             return; // para que no avance al siguiente formulario
         }
           //CODIGO PARA EL GRUPO GENERO
           String respuesta1 ="Usted es de sexo: ";
           if(rbmasculino.isSelected()){
               respuesta1 = respuesta1 + " masculino.";
           }
           else if(rbfemenino.isSelected()){
               respuesta1 = respuesta1 + " femenino.";
           }
           //CODIGO FECHA DE NACIMIENTO
           String dia = (String) cbbdia.getSelectedItem();
           String mes = (String) cbbmes.getSelectedItem();
           String anio = (String) cbbanio.getSelectedItem();
           
           //CODIGO DEL ESTADO CIVIL
           String respuesta2 = "Usted es: ";
           String respuesta3 = "Usted no establecio su estado civil: ";
           
           if (chksoltero.isSelected()){
               if(rbmasculino.isSelected()){
              respuesta2 = respuesta2 + "soltero";
          } 
               else {
                   respuesta2 = respuesta2 + "soltera";
               }
           }
           
           if (chkcasado.isSelected()){
               if(rbmasculino.isSelected()){
              respuesta2 = respuesta2 + "casado";
          } 
               else {
                   respuesta2 = respuesta2 + "casada";
               }
           }
            
           
               
    
             //CODIGO PARA VISUALIZAR RESULTADO EN FORMULARIO  2
             //CODIGO PARA EVITAR SELECCIONAR AMBOS ESTADOS CIVILES
             
             if ((chksoltero.isSelected())&&(chkcasado.isSelected())==true){
                 JOptionPane.showMessageDialog(null, "No es posible seleccionar ambos estados; seleccione uno de ellos o ninguno.");
                 return;// para que no avanze al siguiente formulario
             }
                 //CODIGO PARA LLAMAR AL FORMULARIO 2
                 Formulario_2 form2 =new Formulario_2();
                 form2.setVisible(true);
                 //CODIGO PARA OCULTAR EL FORMULARIO PRESENTE
                 this.setVisible(false);
                 //CODIGO PARA VISUALIZAR LOS DATOS GENERALES
                form2.lblnombre1.setText("Tu primer nombre es:" + nombre1);
                form2.lblapellido1.setText("Tu primer apellido es:" + apellidop);
                form2.lblapellido2.setText("Tu segundo apellido es:" + apellidom);    
                
                
            //CODIGO PARA VISUALIZAR RESPUESTA EN EL NOMBRE 2
            if(txtnom2.getText().equals("")){
                form2.lblnombre2.setText("No ingresas tu segundo nombre");
            }else{
                form2.lblnombre2.setText("Tu segundo nombre es " +nombre2);
            }
            
            //CODIGO PARA EL GRUPO GENERO
            form2.lblsexo.setText(respuesta1 );
            // CODIGO PARA LA FECHA DE NACIMIENTO
            form2.lblfecha.setText("Naciste el: " + dia + " de " + mes + " del " + anio );
            //CODIGO DEL ESTADO CIVIL
            if((chksoltero.isSelected()) || (chkcasado.isSelected())==true){
                form2.lblcivil.setText(respuesta2);
            } else{
                form2.lblcivil.setText(respuesta3);
            }
                
    }//GEN-LAST:event_btnprocesarActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        
        //CODIGO PARA LIMPIAR DATOS GENERALES
        txtapp.setText("");
        txtapm.setText("");
        txtnom1.setText("");
        txtnom2.setText("");
        
        //CODIGO PARA LIMPIAR EL GRUPO GENERO
        buttonGroup1.clearSelection(); // PARA LIMPIAR CUALQUIER SELECCION
        rbmasculino.setSelected(true); // PARA DEJAR ESTABLECIDO MASCULINO POR DEFECTO
        
        //CODIGO PARA LIMPIAR FECHA DE NACIMIENTO
        
        cbbdia.setSelectedItem("01");
        cbbmes.setSelectedItem("enero");
        cbbanio.setSelectedItem("1980");
        //CODIGO PARA LIMPIAR EL ESTADO CIVIL
        
        if(chksoltero.isSelected()){
            chksoltero.setSelected(false);
        }
        if(chkcasado.isSelected()){
            chkcasado.setSelected(false);
        }

        
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnprocesar;
    private javax.swing.JButton btnsalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbanio;
    private javax.swing.JComboBox<String> cbbdia;
    private javax.swing.JComboBox<String> cbbmes;
    private javax.swing.JCheckBox chkcasado;
    private javax.swing.JCheckBox chksoltero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JRadioButton rbfemenino;
    private javax.swing.JRadioButton rbmasculino;
    private javax.swing.JTextField txtapm;
    private javax.swing.JTextField txtapp;
    private javax.swing.JTextField txtnom1;
    private javax.swing.JTextField txtnom2;
    // End of variables declaration//GEN-END:variables
}
