/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario_grafico_videos_20;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author C.andres
 */
public class Formulario_2 extends javax.swing.JFrame {

    /**
     * Creates new form Formulario_1
     */
    public Formulario_2() {
        initComponents();
        //CODIGO PARA UBICAR FORMULARIO AL CENTRO DE LA PANTALLA
        this.setLocationRelativeTo(null);
        //CODIGO PARA AJUSTAR IMAGEN AL LABEL
        
       /* ImageIcon fondo =new ImageIcon("src/newpackage\\paisaje.png");
        Icon icono = new ImageIcon(fondo.getImage().getScaledInstance(lblfondo.getWidth(), lblfondo.getHeight(), Image.SCALE_DEFAULT));
      lblfondo.setIcon(icono);
      this.repaint();*/
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnsalir = new javax.swing.JButton();
        lblnombre1 = new javax.swing.JLabel();
        lblnombre2 = new javax.swing.JLabel();
        lblapellido1 = new javax.swing.JLabel();
        lblapellido2 = new javax.swing.JLabel();
        lblsexo = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        lblcivil = new javax.swing.JLabel();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DATOS DEL FORMULARIO");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("RESULTADOS DEL FORMULARIO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/next.png"))); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.setOpaque(false);
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        lblnombre1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblnombre1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblnombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 92, 230, 20));

        lblnombre2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblnombre2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblnombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 122, 230, 20));

        lblapellido1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblapellido1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblapellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 152, 230, 20));

        lblapellido2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblapellido2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblapellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 182, 230, 20));

        lblsexo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblsexo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblsexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 240, 20));

        lblfecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblfecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 240, 20));

        lblcivil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcivil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblcivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 240, 20));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/paisaje.png"))); // NOI18N
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
               System.exit(0);

    }//GEN-LAST:event_btnsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lblapellido1;
    public javax.swing.JLabel lblapellido2;
    public javax.swing.JLabel lblcivil;
    public javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblfondo;
    public javax.swing.JLabel lblnombre1;
    public javax.swing.JLabel lblnombre2;
    public javax.swing.JLabel lblsexo;
    // End of variables declaration//GEN-END:variables
}
